# Code generated by river.codegen. DO NOT EDIT.
from pydantic import BaseModel
from typing import Literal

import replit_river as river


from .agentToolLanguageServer import AgenttoollanguageserverService
from .aiExec import AiexecService
from .conmanFilesystem import ConmanfilesystemService
from .replspaceApi import ReplspaceapiService
from .shellExec import ShellexecService


class foo:
    def __init__(self, client: river.Client[Literal[None]]):
        self.aiExec = AiexecService(client)
        self.agentToolLanguageServer = AgenttoollanguageserverService(client)
        self.shellExec = ShellexecService(client)
        self.replspaceApi = ReplspaceapiService(client)
        self.conmanFilesystem = ConmanfilesystemService(client)
