# Code generated by river.codegen. DO NOT EDIT.
from collections.abc import AsyncIterable, AsyncIterator
from typing import Any
import datetime

from pydantic import TypeAdapter

from replit_river.error_schema import RiverError, RiverErrorTypeAdapter
import replit_river as river


from .stream_method import (
    Stream_MethodInput,
    Stream_MethodOutput,
    Stream_MethodOutputTypeAdapter,
    encode_Stream_MethodInput,
)
from .emit_error import Emit_ErrorErrors

boolTypeAdapter: TypeAdapter[bool] = TypeAdapter(bool)


Emit_ErrorErrorsTypeAdapter: TypeAdapter[Emit_ErrorErrors] = TypeAdapter(
    Emit_ErrorErrors
)


class Test_ServiceService:
    def __init__(self, client: river.Client[Any]):
        self.client = client

    async def stream_method(
        self,
        inputStream: AsyncIterable[Stream_MethodInput],
    ) -> AsyncIterator[Stream_MethodOutput | RiverError | RiverError]:
        return self.client.send_stream(
            "test_service",
            "stream_method",
            None,
            inputStream,
            None,
            encode_Stream_MethodInput,
            lambda x: Stream_MethodOutputTypeAdapter.validate_python(
                x  # type: ignore[arg-type]
            ),
            lambda x: RiverErrorTypeAdapter.validate_python(
                x  # type: ignore[arg-type]
            ),
        )

    async def emit_error(
        self,
        inputStream: AsyncIterable[int],
    ) -> AsyncIterator[bool | Emit_ErrorErrors | RiverError]:
        return self.client.send_stream(
            "test_service",
            "emit_error",
            None,
            inputStream,
            None,
            lambda x: x,
            lambda x: boolTypeAdapter.validate_python(
                x  # type: ignore[arg-type]
            ),
            lambda x: Emit_ErrorErrorsTypeAdapter.validate_python(
                x  # type: ignore[arg-type]
            ),
        )
