# Code generated by river.codegen. DO NOT EDIT.
from pydantic import BaseModel
from typing import Literal

import replit_river as river


from .enumService import EnumserviceService


class foo:
    def __init__(self, client: river.Client[Literal[None]]):
        self.enumService = EnumserviceService(client)
