# Code generated by river.codegen. DO NOT EDIT.
from collections.abc import AsyncIterable, AsyncIterator
from typing import Any
import datetime

from pydantic import TypeAdapter

from replit_river.error_schema import RiverError, RiverErrorTypeAdapter
import replit_river as river


from .getTree import (
    GettreeInput,
    GettreeOutput,
    GettreeOutputTypeAdapter,
    encode_GettreeInput,
)


class RecursiveserviceService:
    def __init__(self, client: river.Client[Any]):
        self.client = client

    async def getTree(
        self,
        input: GettreeInput,
        timeout: datetime.timedelta,
    ) -> GettreeOutput:
        return await self.client.send_rpc(
            "recursiveService",
            "getTree",
            input,
            encode_GettreeInput,
            lambda x: GettreeOutputTypeAdapter.validate_python(
                x  # type: ignore[arg-type]
            ),
            lambda x: RiverErrorTypeAdapter.validate_python(
                x  # type: ignore[arg-type]
            ),
            timeout,
        )
