# Code generated by river.codegen. DO NOT EDIT.
from collections.abc import AsyncIterable, AsyncIterator
import datetime
from typing import (
    Any,
    Literal,
    Mapping,
    NotRequired,
    TypedDict,
)
from typing_extensions import Annotated

from pydantic import BaseModel, Field, TypeAdapter, WrapValidator
from replit_river.error_schema import RiverError
from replit_river.client import (
    RiverUnknownError,
    translate_unknown_error,
    RiverUnknownValue,
    translate_unknown_value,
)

import replit_river as river


def encode_GettreeInput(
    x: "GettreeInput",
) -> Any:
    return {
        k: v
        for (k, v) in (
            {
                "rootId": x.get("rootId"),
            }
        ).items()
        if v is not None
    }


class GettreeInput(TypedDict):
    rootId: str


class GettreeOutput(BaseModel):
    children: list["GettreeOutput"]
    id: str
    name: str


GettreeOutputTypeAdapter: TypeAdapter[GettreeOutput] = TypeAdapter(GettreeOutput)
