# Code generated by river.codegen. DO NOT EDIT.
from pydantic import BaseModel
from typing import Literal

import replit_river as river


from .recursiveService import RecursiveserviceService


class RecursiveClient:
    def __init__(self, client: river.Client[Literal[None]]):
        self.recursiveService = RecursiveserviceService(client)
