# Code generated by river.codegen. DO NOT EDIT.
from collections.abc import AsyncIterable, AsyncIterator
from typing import Any
import datetime

from pydantic import TypeAdapter

from replit_river.error_schema import RiverError, RiverErrorTypeAdapter
import replit_river as river


from .anyof_mixed_method import (
    Anyof_Mixed_MethodInput,
    Anyof_Mixed_MethodOutput,
    Anyof_Mixed_MethodOutputTypeAdapter,
    encode_Anyof_Mixed_MethodInput,
    encode_Anyof_Mixed_MethodInputNumber_Or_String,
    encode_Anyof_Mixed_MethodInputRun_Command,
    encode_Anyof_Mixed_MethodInputValue_Or_Null,
)


class Test_ServiceService:
    def __init__(self, client: river.Client[Any]):
        self.client = client

    async def anyof_mixed_method(
        self,
        input: Anyof_Mixed_MethodInput,
        timeout: datetime.timedelta,
    ) -> Anyof_Mixed_MethodOutput:
        return await self.client.send_rpc(
            "test_service",
            "anyof_mixed_method",
            input,
            encode_Anyof_Mixed_MethodInput,
            lambda x: Anyof_Mixed_MethodOutputTypeAdapter.validate_python(
                x  # type: ignore[arg-type]
            ),
            lambda x: RiverErrorTypeAdapter.validate_python(
                x  # type: ignore[arg-type]
            ),
            timeout,
        )
