# Code generated by river.codegen. DO NOT EDIT.
from collections.abc import AsyncIterable, AsyncIterator
import datetime
from typing import (
    Any,
    Literal,
    Mapping,
    NotRequired,
    TypedDict,
    cast,
)
from typing_extensions import Annotated

from pydantic import BaseModel, Field, TypeAdapter, WrapValidator
from replit_river.error_schema import RiverError
from replit_river.client import (
    RiverUnknownError,
    translate_unknown_error,
    RiverUnknownValue,
    translate_unknown_value,
)

import replit_river as river


Anyof_Mixed_MethodInputNumber_Or_String = float | str


def encode_Anyof_Mixed_MethodInputNumber_Or_String(
    x: "Anyof_Mixed_MethodInputNumber_Or_String",
) -> Any:
    return x


def encode_Anyof_Mixed_MethodInputRun_CommandAnyOf_0(
    x: "Anyof_Mixed_MethodInputRun_CommandAnyOf_0",
) -> Any:
    return {
        k: v
        for (k, v) in (
            {
                "args": x.get("args"),
                "env": x.get("env"),
            }
        ).items()
        if v is not None
    }


class Anyof_Mixed_MethodInputRun_CommandAnyOf_0(TypedDict):
    args: list[str]
    env: NotRequired[dict[str, str] | None]


Anyof_Mixed_MethodInputRun_Command = (
    Anyof_Mixed_MethodInputRun_CommandAnyOf_0 | str | list[str]
)


def encode_Anyof_Mixed_MethodInputRun_Command(
    x: "Anyof_Mixed_MethodInputRun_Command",
) -> Any:
    return (
        encode_Anyof_Mixed_MethodInputRun_CommandAnyOf_0(x)
        if isinstance(x, dict)
        else x
        if isinstance(x, str)
        else list(x)
    )


Anyof_Mixed_MethodInputValue_Or_Null = str | None


def encode_Anyof_Mixed_MethodInputValue_Or_Null(
    x: "Anyof_Mixed_MethodInputValue_Or_Null",
) -> Any:
    return x


def encode_Anyof_Mixed_MethodInput(
    x: "Anyof_Mixed_MethodInput",
) -> Any:
    return {
        k: v
        for (k, v) in (
            {
                "number_or_string": encode_Anyof_Mixed_MethodInputNumber_Or_String(
                    x["number_or_string"]
                )
                if "number_or_string" in x and x["number_or_string"]
                else None,
                "run_command": encode_Anyof_Mixed_MethodInputRun_Command(
                    x["run_command"]
                ),
                "value_or_null": encode_Anyof_Mixed_MethodInputValue_Or_Null(
                    x["value_or_null"]
                )
                if "value_or_null" in x and x["value_or_null"]
                else None,
            }
        ).items()
        if v is not None
    }


class Anyof_Mixed_MethodInput(TypedDict):
    number_or_string: NotRequired[Anyof_Mixed_MethodInputNumber_Or_String | None]
    run_command: Anyof_Mixed_MethodInputRun_Command
    value_or_null: NotRequired[Anyof_Mixed_MethodInputValue_Or_Null | None]


class Anyof_Mixed_MethodOutput(BaseModel):
    success: bool


Anyof_Mixed_MethodOutputTypeAdapter: TypeAdapter[Anyof_Mixed_MethodOutput] = (
    TypeAdapter(Anyof_Mixed_MethodOutput)
)
