# Code generated by river.codegen. DO NOT EDIT.
from collections.abc import AsyncIterable, AsyncIterator
import datetime
from typing import (
    Any,
    Literal,
    Mapping,
    NotRequired,
    TypedDict,
)
from typing_extensions import Annotated

from pydantic import BaseModel, Field, TypeAdapter, WrapValidator
from replit_river.error_schema import RiverError
from replit_river.client import (
    RiverUnknownError,
    translate_unknown_error,
    RiverUnknownValue,
    translate_unknown_value,
)

import replit_river as river


class InitInit(BaseModel):
    pass


class InitInputOneOf_closeFile(BaseModel):
    kind: Annotated[Literal["closeFile"], Field(alias="$kind")] = "closeFile"
    filename: str
    nonce: str


class InitInputOneOf_githubToken(BaseModel):
    kind: Annotated[Literal["githubToken"], Field(alias="$kind")] = "githubToken"
    nonce: str
    token: str | None = None


class InitInputOneOf_sshToken0(BaseModel):
    kind: Annotated[Literal["sshToken"], Field(alias="$kind")] = "sshToken"
    SSHHostname: str
    nonce: str
    token: str


class InitInputOneOf_sshToken1(BaseModel):
    kind: Annotated[Literal["sshToken"], Field(alias="$kind")] = "sshToken"
    error: str
    nonce: str


class InitInputOneOf_allowDefaultBucketAccessResultOneOf_error(BaseModel):
    message: str
    status: Literal["error"]


class InitInputOneOf_allowDefaultBucketAccessResultOneOf_ok(BaseModel):
    bucketId: str
    sourceReplId: str
    status: Literal["ok"]
    targetReplId: str


InitInputOneOf_allowDefaultBucketAccessResult = (
    InitInputOneOf_allowDefaultBucketAccessResultOneOf_error
    | InitInputOneOf_allowDefaultBucketAccessResultOneOf_ok
)


class InitInputOneOf_allowDefaultBucketAccess(BaseModel):
    kind: Annotated[Literal["allowDefaultBucketAccess"], Field(alias="$kind")] = (
        "allowDefaultBucketAccess"
    )
    nonce: str
    result: InitInputOneOf_allowDefaultBucketAccessResult


InitInput = (
    InitInputOneOf_closeFile
    | InitInputOneOf_githubToken
    | InitInputOneOf_sshToken0
    | InitInputOneOf_sshToken1
    | InitInputOneOf_allowDefaultBucketAccess
)


class InitOutput(BaseModel):
    pass


InitOutputTypeAdapter: TypeAdapter[InitOutput] = TypeAdapter(InitOutput)


class InitErrors(RiverError):
    pass


InitErrorsTypeAdapter: TypeAdapter[InitErrors] = TypeAdapter(InitErrors)


InitInitTypeAdapter: TypeAdapter[InitInit] = TypeAdapter(InitInit)


InitInputTypeAdapter: TypeAdapter[InitInput] = TypeAdapter(InitInput)
